---

services:
  web:
    build: ./web
    ports:
      - "4567:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/markr
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: markr
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

